<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.13</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>spring-boot-docker-complete</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>spring-boot-docker-complete</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
 		<!-- Note: If your ACR name contains upper case characters, be sure to convert them to lower case characters. -->
   		<docker.image.prefix>quayvitran.azurecr.io</docker.image.prefix>
   		<jib-maven-plugin.version>3.4.4</jib-maven-plugin.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
			<artifactId>jib-maven-plugin</artifactId>
			<groupId>com.google.cloud.tools</groupId>
			<version>${jib-maven-plugin.version}</version>
			<configuration>
				<from>
					<image>mcr.microsoft.com/openjdk/jdk:17-ubuntu</image>
				</from>
				<to>
					<image>${docker.image.prefix}/gs-spring-boot-docker</image>
				</to>
			</configuration>
			</plugin>
		</plugins>
	</build>

</project>
